version: "3.7"

services:

    php:
        image: php
        container_name: php
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        ports:
            - 9000:9000
        networks:
            - backend

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: viblo-database
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - backend

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8181:80
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        networks:
            - backend

    nginx:
        image: nginx:1.25.1
        container_name: nginx
        volumes:
            - ./backend:/var/www/html/backend
            - ./frontend:/var/www/html/frontend
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/log/:/var/log/nginx
        depends_on:
            - php
            - mysql
        ports:
            - 8000:8000
        networks:
            - backend
            - frontend

    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - backend

    node:
        container_name: nodejs
        image: nodejs
        stdin_open: true
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./frontend:/app
        networks:
            - frontend

networks:
    backend:
    frontend:
